const ACTION_TYPES = {
  HEADER__SETTINGS_OPEN: 'h_s_o_0',
  HEADER__SETTINGS_CLOSE: 'h_s_o_1',
  SETTINGS_PAGE__FILE_EXPLORER_MODAL_OPEN: 's_p_f_e_m_o_0',
  SETTINGS_PAGE__FILE_EXPLORER_MODAL_CLOSE: 's_p_f_e_m_o_1'
};

export default ACTION_TYPES;
